---
# Install
- name: Create target dir
  file:
    path: /usr/local/sbin
    group: root
    owner: root
    state: directory
    mode: 0755
  become: true

- name: Download script
  get_url:
      url: https://raw.githubusercontent.com/zfsonlinux/zfs-auto-snapshot/master/src/zfs-auto-snapshot.sh
      force: "{{ autosnap_update }}"
      mode: 0755
      dest: "{{ autosnap_bin }}"
      group: root
      owner: root
  become: true

- name: Download man page
  get_url:
      url: https://raw.githubusercontent.com/zfsonlinux/zfs-auto-snapshot/master/src/zfs-auto-snapshot.8
      force: "{{ autosnap_update }}"
      mode: 0644
      dest: /usr/share/man/man8/zfs-auto-snapshot.8
      group: root
      owner: root
  become: true

- name: Set up cron files
  become: true
  template:
    src: zfs-auto-snapshot.j2
    dest: "/etc/cron.{{ item.label }}/zfs-auto-snapshot"
    owner: root
    group: root
    mode: 0755
  with_items:
    - label: hourly
      keep: "{{ zfs_keep_hourly }}"
    - label: daily
      keep: "{{ zfs_keep_daily }}"
    - label: weekly
      keep: "{{ zfs_keep_weekly }}"
    - label: monthly
      keep: "{{ zfs_keep_monthly }}"

- name: Set up frequent cron file
  template:
    src: zfs-auto-snapshot.frequent.j2
    dest: /etc/cron.d/zfs-auto-snapshot
    owner: root
    group: root
    mode: 0755
  become: true

# Set the ZFS properties
- name: Update ZFS 'enabled' properties
  command: zfs set com.sun:auto-snapshot={{ item.value.enabled | default(true) | lower }} {{ item.key }}
  become: true
  with_dict: "{{ zfs_datasets }}"

- name: Update ZFS frequent properties
  command: zfs set com.sun:auto-snapshot:frequent={{ item.value['frequent'] | default(false) | lower }} {{ item.key }}
  become: true
  with_dict: "{{ zfs_datasets }}"
- name: Update ZFS hourly properties
  command: zfs set com.sun:auto-snapshot:hourly={{ item.value['hourly'] | default(false) | lower }} {{ item.key }}
  become: true
  with_dict: "{{ zfs_datasets }}"
- name: Update ZFS daily properties
  command: zfs set com.sun:auto-snapshot:daily={{ item.value['daily'] | default(false) | lower }} {{ item.key }}
  become: true
  with_dict: "{{ zfs_datasets }}"
- name: Update ZFS weekly properties
  command: zfs set com.sun:auto-snapshot:weekly={{ item.value['weekly'] | default(false) | lower }} {{ item.key }}
  become: true
  with_dict: "{{ zfs_datasets }}"
- name: Update ZFS monthly properties
  command: zfs set com.sun:auto-snapshot:monthly={{ item.value['monthly'] | default(false) | lower }} {{ item.key }}
  become: true
  with_dict: "{{ zfs_datasets }}"
